### ISSUE TITLE
Auto Fill Name in json creator

### ISSUE THREAD

**Issue by Bluscream** [DefyTheRush/Garrys-Mod-Workshop-Utility#4]
https://github.com/DefyTheRush/Garrys-Mod-Workshop-Utility/blob/master/GarrysModWorkshopUtil/AddonJsonUI.cs#L63

![image](https://user-images.githubusercontent.com/3318223/80655106-2933e280-8a7e-11ea-8a4f-956d2e444983.png)

**Comment by HonestResolv3** [comment]
I do not know how I have not seen this issue, I am watching the repository as well so I would have gotten a notification, I will be looking into this 

EDIT: How did you reproduce this? I tried to add a new directory and I see that it did not change the Addon Title area. Unless this is maybe a request or a feature of filling in the title based on the output

**Comment by Bluscream** [comment]
Yeah sorry for not making thus more clear, its a feature request ^^

**Comment by HonestResolv3** [comment]
Ah gotcha, I will work on that. My plan for that is to make it a toggle where you can make it auto-fill if you want to, or not

**Comment by HonestResolv3** [comment]
V4.5.2 is out which implemented that feature
